// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Task struct {
	ID             int32
	Type           int32
	Value          int32
	State          string
	CreationTime   time.Time
	LastUpdateTime time.Time
}
